name: Continuous Integration

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  continuous-integration:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - name: Run babashka-test-action
        uses: liquidz/babashka-test-action@v1
        with:
          source-paths: 'src'
          test-paths: 'test'
          test-file-pattern: '_test.clj$'
